config/routes.rb
GuardEventApp::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'
  get '/history' => 'home#history'
  get '/photos' => 'home#photos'
  get '/secure_info' => 'devise_authenticated#user_info'
  get '/admin_dashboard' => 'devise_authenticated#admin_dashboard'
  get '/request_access' => 'requests#create'
  # post '/submit_request' => 'requests#create_request'


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  # attr_accessible :title, :body
end

app/models/user_request.rb
class UserRequest < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :password, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devise_authenticated_controller.rb
class DeviseAuthenticatedController < ApplicationController

  before_filter :authenticate_user! # TODO uncomment after testing

  # This is where we would fetch info from the google calendar api to see
  # all events for this particular unit
  def user_info

  end

  # all the admin pro
  def admin_dashboard


  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    eb_client = EventbriteClient.new( {app_key: 'JLAH2BUMQXLFQBPZZY', user_key: '1421680383133097458080'})
    events = eb_client.user_list_events["events"]
    @html_array = get_event_html events
    @html_array
  end

  def history

  end

  def photos

  end


  protected

  def get_event_html(events_array)
    event_html_array = []

    events_array.each do |event_hash|
      event_html_array << EventbriteWidgets::ticketWidget(event_hash["event"])
    end

    event_html_array

  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def create

  end

  def create_request

    UserRequest.create({
      first_name: params[:first_name], last_name: params[:last_name],
      email: params[:email], password: params[:password]
      })
    # create user_request
    # redirect to home page
    # alert user that request got submitted and expect and expect an email when approved
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devise_authenticated/user_info.html.erb
<div class="user_info">

  <div class="calendar">
    <iframe src="https://www.google.com/calendar/embed?src=uc58qi8dg362flulh6513nt2ig%40group.calendar.google.com&ctz=America/New_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
  </div>

  <h3>Announcements</h3>

















</div>

app/views/home/history.html.erb
<div class="history">

  <h1>History PAGE</h1>



</div>

app/views/home/index.html.erb
<div class="index">

  <% if @html_array.empty? %>

    <h1> Sorry no upcoming events at the moment, check back later</h1>

  <% else %>

    <% @html_array.each do |html| %>
      <div class="upcoming-event"> <%= CGI.unescapeHTML(html).html_safe %> <div>
    <% end %>

  <%end%>



</div>

app/views/home/photos.html.erb
<div class='photos'>

  <h1>PHOTOES</h1>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuardEventApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <header>
      <%=link_to("home", "/")%>
      <br>
      <%=link_to("History", history_path)%>
      <br>
      <%=link_to("Photos", photos_path)%>

    </header>
    <p class="notice"><%= notice %></p>


    <%= yield %>
  </div>
</body>
</html>

app/views/requests/create.html.erb
<div class='create-request'>



  <h1>MAKE A REQUEST</h1>




  <%= form_tag("/submit_request", method: "post") do %>
    <%= label_tag(:first_name, "First Name:") %>
    <%= text_field_tag(:first_name) %><br>

    <%= label_tag(:last_name, "Last Name:") %>
    <%= text_field_tag(:last_name) %><br>

    <%= label_tag(:email, "Email:") %>
    <%= email_field_tag(:email) %><br>

    <%= label_tag(:password, "Password for:") %>
    <%= password_field_tag(:password) %><br>

    <%= label_tag(:password_confirmation, "Confirm Password:") %>
    <%= password_field_tag(:password_confirmation) %><br>


  <%= submit_tag("Submit Request") %>
<% end %>














</div>